# Mock Dataset structuration and synthesis

In [19]:
import pandas as pd

# Correcting the data and adding more entries
data = {
    "Customer ID": list(range(1, 101)),
    "Customer Name": [
        "Acme Corporation", "Globex Corporation", "Soylent Corp", "Initech", "Bluth Company",
        "Umbrella Corp", "Hooli", "Vehement Capital", "Massive Dynamic", "Wonka Industries",
        "Stark Industries", "Wayne Enterprises", "Duff Brewing", "Gekko & Co", "Vandelay Industries",
        "Kwik-E-Mart", "Reynholm Industries", "Kruger Industrial", "Strickland Propane", "Gringotts",
        "Oscorp", "Choam", "Sirius Cybernetics", "Harlington-Straker", "Nakatomi Trading",
        "Tyrell Corporation", "Cyberdyne Systems", "Planet Express", "Soylent Corporation", "Pierce & Pierce",
        "Google LLC", "Apple Inc.", "Microsoft Corporation", "Amazon.com, Inc.", "Facebook, Inc.",
        "Tesla, Inc.", "Berkshire Hathaway Inc.", "Visa Inc.", "Johnson & Johnson", "Samsung Electronics",
        "ExxonMobil Corporation", "Walmart Inc.", "Pfizer Inc.", "Chevron Corporation", "Coca-Cola Company",
        "Toyota Motor Corporation", "Daimler AG", "Intel Corporation", "Verizon Communications", "Boeing Company",
        "Oracle Corporation", "Nike, Inc.", "Sony Corporation", "LG Electronics Inc.", "Royal Dutch Shell plc",
        "BP plc", "General Electric Company", "Honeywell International", "Citigroup Inc.", "American Express Company",
        "Petrobras", "América Móvil", "Vale S.A.", "Itaú Unibanco Holding", "MercadoLibre",
        "Grupo Bimbo", "Bancolombia", "Grupo México", "Embraer S.A.", "Cemex",
        "LATAM Airlines Group", "Grupo Falabella", "Tenaris", "Ultrapar Participações S.A.", "Grupo Carso",
        "Grupo Argos", "S.A.C.I. Falabella", "Arcos Dorados Holdings Inc.", "JBS S.A.", "Grupo Aeroportuario del Pacífico",
        "Copel", "Braskem", "Grupo Antofagasta Minerals", "Ecopetrol", "Banco do Brasil",
        "Odebrecht", "YPF (Yacimientos Petrolíferos Fiscales)", "Marfrig Global Foods", "Grupo Nutresa", "SQM (Sociedad Química y Minera de Chile)",
        "Petrobras", "Vale S.A.", "América Móvil", "Itaú Unibanco Holding", "Grupo México",
        "Banco Bradesco", "Banco Santander Brasil", "Grupo Bimbo", "Grupo Financiero Banorte", "Suzano S.A."
    ],
    "Customer Address": [
        "123 Elm St, Springfield, IL", "456 Oak St, Metropolis, IN", "789 Pine St, Gotham, NY",
        "101 Maple Ave, Smallville, KS", "102 Birch St, Hill Valley, CA",
        "103 Cedar St, Sunnydale, CA", "104 Palm St, Atlantis, FL", "105 Spruce St, Vice City, FL",
        "106 Iron St, Star City, WA", "107 Steel St, South Park, CO",
        "108 Silver St, Central City, MO", "109 Gold St, Emerald City, MI", "110 Copper St, Kings Landing, CA",
        "111 Zinc St, Springfield, VT", "112 Quartz St, Quahog, RI",
        "113 Cobalt St, Twin Peaks, WA", "114 Nickel St, Charming, CA", "115 Tin St, Eureka, NV",
        "116 Lead St, Neptune, CA", "117 Mercury St, Gotham, NJ",
        "118 Platinum St, Metropolis, TX", "119 Diamond St, Pandora, AZ", "120 Graphite St, Bon Temps, LA",
        "121 Silicon St, Silent Hill, ME", "122 Boron St, Cabot Cove, ME",
        "123 Argon St, Mystic Falls, VA", "124 Neon St, Twin Peaks, NV", "125 Helium St, New New York, NY",
        "126 Lithium St, Twin Peaks, WA", "127 Krypton St, Smallville, TX",
        "1600 Amphitheatre Parkway, Mountain View, CA", "1 Apple Park Way, Cupertino, CA", "One Microsoft Way, Redmond, WA",
        "410 Terry Ave N, Seattle, WA", "1 Hacker Way, Menlo Park, CA",
        "3500 Deer Creek Road, Palo Alto, CA", "3555 Farnam St, Omaha, NE", "900 Metro Center Blvd, Foster City, CA",
        "One Johnson & Johnson Plaza, New Brunswick, NJ", "129 Samsung-Ro, Yeongtong-Gu, Suwon-si, South Korea",
        "5959 Las Colinas Boulevard, Irving, TX", "702 SW 8th St, Bentonville, AR", "235 East 42nd Street, New York, NY",
        "6001 Bollinger Canyon Rd, San Ramon, CA", "1 Coca Cola Plaza, Atlanta, GA", "1 Toyota-Cho, Toyota City, Japan",
        "Mercedesstraße 120, Stuttgart, Germany", "2200 Mission College Blvd, Santa Clara, CA", "1095 Avenue of the Americas, New York, NY",
        "100 N Riverside Plaza, Chicago, IL", "500 Oracle Parkway, Redwood City, CA", "One Bowerman Drive, Beaverton, OR",
        "1-7-1 Konan, Minato-ku, Tokyo, Japan", "20 Yeouido-dong, Yeongdeungpo-gu, Seoul, South Korea", "Carel van Bylandtlaan 16, The Hague, Netherlands",
        "1 St James's Square, London, UK", "5 Necco St, Boston, MA", "300 South Tryon Street, Charlotte, NC",
        "388 Greenwich St, New York, NY", "200 Vesey St, New York, NY",
        "Avenida República do Chile, 65, Rio de Janeiro, Brazil", "Lago Zurich 245, Plaza Carso, Mexico City, Mexico", "Praia de Botafogo, 186, Rio de Janeiro, Brazil",
        "Praça Alfredo Egydio de Souza Aranha, 100, São Paulo, Brazil", "Arias 3751, Buenos Aires, Argentina",
        "Prolongación Paseo de la Reforma 1000, Mexico City, Mexico", "Carrera 48 # 26-85, Medellín, Colombia", "Campos Elíseos 400, Lomas de Chapultepec, Mexico City, Mexico",
        "Av. Brig. Faria Lima, 2170, São José dos Campos, Brazil", "Av. Ricardo Margáin Zozaya 325, San Pedro, Mexico",
        "Av. Americo Vespucio 901, Renca, Santiago, Chile", "Rosas 1665, Santiago, Chile", "Diagonal 185bis, Buenos Aires, Argentina",
        "Rua Gomes de Carvalho, 1336, São Paulo, Brazil", "Lago Zurich 245, Plaza Carso, Mexico City, Mexico",
        "Carrera 43A #1A Sur - 143, Medellín, Colombia", "Rosas 1665, Santiago, Chile", "Dr. Luis Bonavita 1294, Montevideo, Uruguay",
        "Avenida Marginal Direita do Tietê, 500, São Paulo, Brazil", "Mariano Otero 1249, Guadalajara, Mexico",
        "Rua Coronel Dulcídio, 800, Curitiba, Brazil", "Rua Lemos Monteiro, 120, São Paulo, Brazil", "Av. Apoquindo 4001, Santiago, Chile",
        "Calle 37 #8-43, Bogotá, Colombia", "SBS Quadra 1 Bloco C, Brasília, Brazil",
        "Av. das Nações Unidas, 8501, São Paulo, Brazil", "Macacha Güemes 515, Buenos Aires, Argentina", "Avenida Chedid Jafet, 222, São Paulo, Brazil",
        "Calle 73 #51-14, Medellín, Colombia", "El Trovador 4285, Las Condes, Santiago, Chile",
        "Avenida República do Chile, 65, Rio de Janeiro, Brazil", "Praia de Botafogo, 186, Rio de Janeiro, Brazil", "Lago Zurich 245, Plaza Carso, Mexico City, Mexico",
        "Praça Alfredo Egydio de Souza Aranha, 100, São Paulo, Brazil", "Campos Elíseos 400, Lomas de Chapultepec, Mexico City, Mexico",
        "Cidade de Deus, Vila Yara, Osasco, Brazil", "Av. Presidente Juscelino Kubitschek, 2041, São Paulo, Brazil", "Prolongación Paseo de la Reforma 1000, Mexico City, Mexico",
        "Av. Revolución 3000, Monterrey, Mexico", "Av. Professor Magalhães Neto, 1752, Salvador, Brazil"
    ],
    "Customer Industrial Sector": [
        "Manufacturing", "Technology", "Food and Beverages", "Software", "Real Estate",
        "Pharmaceuticals", "Technology", "Finance", "Biotechnology", "Food Processing",
        "Advanced Technology", "Conglomerate", "Beverages", "Finance", "Latex Manufacturing",
        "Retail", "IT Services", "Smelting", "Propane and Propane Accessories", "Banking",
        "Chemicals", "Trade", "Robotics", "Film Studio", "Import/Export",
        "Biotech", "Defense", "Delivery Services", "Food Production", "Investment Banking",
        "Technology", "Technology", "Technology", "E-commerce", "Social Media",
        "Automotive", "Conglomerate", "Financial Services", "Pharmaceuticals", "Electronics",
        "Oil and Gas", "Retail", "Pharmaceuticals", "Oil and Gas", "Beverages",
        "Automotive", "Automotive", "Semiconductors", "Telecommunications", "Aerospace and Defense",
        "Technology", "Apparel", "Electronics", "Electronics", "Oil and Gas",
        "Oil and Gas", "Conglomerate", "Conglomerate", "Financial Services", "Financial Services",
        "Oil and Gas", "Telecommunications", "Mining", "Banking", "E-commerce",
        "Food Processing", "Financial Services", "Conglomerate", "Aerospace and Defense", "Construction",
        "Aviation", "Retail", "Manufacturing", "Chemicals", "Conglomerate",
        "Cement and Energy", "Retail", "Fast Food", "Food Processing", "Aviation",
        "Energy", "Petrochemicals", "Mining", "Oil and Gas", "Banking",
        "Construction", "Oil and Gas", "Food Processing", "Food and Beverages", "Chemicals",
        "Oil and Gas", "Mining", "Telecommunications", "Banking", "Mining",
        "Banking", "Banking", "Food Processing", "Banking", "Pulp and Paper"
    ]
}

from unidecode import unidecode

# Assuming 'data' is already defined
df = pd.DataFrame(data)

# Apply unidecode to all string columns
for col in df.select_dtypes(include=[object]):
    df[col] = df[col].apply(lambda x: unidecode(x) if isinstance(x, str) else x)

# Saving the DataFrame to a CSV file
csv_file_path = "./Sample_Dataset/Primary_Reference_Table.csv"
df.to_csv(csv_file_path, index=False)

csv_file_path

'./Sample_Dataset/Primary_Reference_Table.csv'

In [20]:
import pandas as pd

fuzzy_data = {
    "Customer ID": [
        1,   # row 1
        2,   # row 2
        3,   # row 3
        4,   # row 4
        5,   # row 5
        6,   # row 6
        7,   # row 7
        8,   # row 8
        9,   # row 9
        10,  # row 10
        11,  # row 11
        12,  # row 12
        13,  # row 13
        14,  # row 14
        15,  # row 15
        16,  # row 16
        17,  # row 17
        18,  # row 18
        19,  # row 19
        20,  # row 20
        21,  # row 21
        22,  # row 22
        23,  # row 23
        24,  # row 24
        25,  # row 25
        26,  # row 26
        27,  # row 27
        28,  # row 28
        29,  # row 29
        30,  # row 30
        31,  # row 31
        32,  # row 32
        33,  # row 33
        34,  # row 34
        35,  # row 35
        36,  # row 36
        37,  # row 37
        38,  # row 38
        39,  # row 39
        40,  # row 40
        41,  # row 41
        42,  # row 42
        43,  # row 43
        44,  # row 44
        45,  # row 45
        46,  # row 46
        47,  # row 47
        48,  # row 48
        49,  # row 49
        50,  # row 50
        51,  # row 51
        52,  # row 52
        53,  # row 53
        54,  # row 54
        55,  # row 55
        56,  # row 56
        57,  # row 57
        58,  # row 58
        59,  # row 59
        60,  # row 60
        61,  # row 61
        62,  # row 62
        63,  # row 63
        64,  # row 64
        65,  # row 65
        66,  # row 66
        67,  # row 67
        68,  # row 68
        69,  # row 69
        70,  # row 70
        71,  # row 71
        72,  # row 72
        73,  # row 73
        74,  # row 74
        75,  # row 75
        76,  # row 76
        77,  # row 77
        78,  # row 78
        79,  # row 79
        80,  # row 80
        81,  # row 81
        82,  # row 82
        83,  # row 83
        84,  # row 84
        85,  # row 85
        86,  # row 86
        87,  # row 87
        88,  # row 88
        89,  # row 89
        90,  # row 90
        91,  # row 91
        92,  # row 92
        93,  # row 93
        94,  # row 94
        95,  # row 95
        96,  # row 96
        97,  # row 97
        98,  # row 98
        99,  # row 99
        100  # row 100
    ],
    "Customer Name": [
        "Acme Cooorporation",               # row 1: typo 'Cooorporation'
        "Globex Corporation",               # row 2: no name typo, left as-is
        "Soylent Corporatoin",              # row 3: typo 'Corporatoin'
        "Initech LLC (Limited Liability)",  # row 4: desabbrev 'LLC' -> '(Limited Liability)'
        "Bluth Company",                    # row 5: no name typo, left as-is
        "Umbrella Corporation",             # row 6: replaced 'Corp' -> 'Corporation'
        "Hooli Incoporated",                # row 7: 'Incorporated' -> 'Incoporated'
        "Vehement Capital",                 # row 8: no change
        "Massive Dynamic",                  # row 9: no change
        "Wonka Industrries",                # row 10: added typo 'Industrries'
        "Stark Industries",                 # row 11: no change
        "Wayne Enterprisses",               # row 12: added typo 'Enterprisses'
        "Duff Brewing Co (Company)",        # row 13: expanded 'Co' -> '(Company)'
        "Gekko and Company",                # row 14: changed '& Co' -> 'and Company'
        "Vandelay Industtries",             # row 15: added typo 'Industtries'
        "Kwik-E-Mart",                      # row 16: no name typo, left as-is
        "Reynholm Industires",              # row 17: added typo 'Industires'
        "Kruger Industrial",                # row 18: no name typo, left as-is
        "Strickland Propanne",              # row 19: typo 'Propanne'
        "Gringotts Bank",                   # row 20: added 'Bank' for clarity
        "Oscorp Incorporated",              # row 21: replaced 'Oscorp' -> 'Oscorp Incorporated'
        "Choam SA (Sociedad Anonima)",      # row 22: desabbrev 'S.A.' -> 'SA (Sociedad Anonima)'
        "Sirius Cybernetics",               # row 23: no name typo, left as-is
        "Harlington-Straker Studios",       # row 24: added 'Studios'
        "Nakatomi Trading LLC",             # row 25: added 'LLC'
        "Tyrell Corporation",               # row 26: no change
        "Cyberdyne Systems Ltd",            # row 27: appended 'Ltd'
        "Planet Exprress",                  # row 28: typo 'Exprress'
        "Soylent Corporation",              # row 29: no change (similar to #3 but left correct)
        "Pierce and Pierce",                # row 30: replaced '&' with 'and'
        "Google Incorporated",              # row 31: replaced 'LLC' -> 'Incorporated'
        "Apple Incorporated",               # row 32: replaced 'Inc.' -> 'Incorporated'
        "Microsoft Corporatoin",            # row 33: typo 'Corporatoin'
        "Amazon.com, Incorporated",         # row 34: replaced 'Inc.' -> 'Incorporated'
        "Facebook, Incorporated",           # row 35: replaced 'Inc.' -> 'Incorporated'
        "Tesla, Incorporated",              # row 36: replaced 'Inc.' -> 'Incorporated'
        "Berkshire Hathaway Incorporated",  # row 37: replaced 'Inc.' -> 'Incorporated'
        "Visa Inc (Incorporated)",          # row 38: expanded 'Inc' -> '(Incorporated)'
        "Johnson and Johnson",              # row 39: replaced '&' -> 'and'
        "Samsung Electronics AG (Aktiengesellschaft)",  # row 40: added 'AG (Aktiengesellschaft)'
        "ExxonMobil Corporatoin",           # row 41: typo 'Corporatoin'
        "Walmart Incorporated",             # row 42: replaced 'Inc.' -> 'Incorporated'
        "Pfizer Incorporated",              # row 43: replaced 'Inc.' -> 'Incorporated'
        "Chevron Corporation",              # row 44: no change
        "Coca-Cola Company",                # row 45: no change
        "Toyota Motor Corporation",         # row 46: no change
        "Daimler AG (Aktiengesellschaft)",  # row 47: expanded 'AG'
        "Intel Corporation",                # row 48: no change
        "Verizon Communicatons",            # row 49: typo 'Communicatons'
        "Boeing Company",                   # row 50: no change
        "Oracle Corporration",              # row 51: typo 'Corporration'
        "Nike, Incorporated",               # row 52: replaced 'Inc.' -> 'Incorporated'
        "Sony Corporation",                 # row 53: no change
        "LG Electronics Incorporated",      # row 54: replaced 'Inc.' -> 'Incorporated'
        "Royal Dutch Shell Public Limited Company",  # row 55: replaced 'plc' -> 'Public Limited Company'
        "BP Public Limited Company",        # row 56: replaced 'plc' -> 'Public Limited Company'
        "General Electric Company",         # row 57: no change
        "Honeywell International",          # row 58: no change
        "Citigroup Incorporated",           # row 59: replaced 'Inc.' -> 'Incorporated'
        "American Express Company",         # row 60: no change
        "Petrobras Sociedad Anonima",       # row 61: replaced with 'Sociedad Anonima'
        "América Móvil",                    # row 62: no change
        "Vale Sociedad Anonima",            # row 63: replaced 'S.A.' -> 'Sociedad Anonima'
        "Itaú Unibanco Holding",            # row 64: no change
        "MercadoLibre",                     # row 65: no change
        "Grupo Bimbo",                      # row 66: no change
        "Bancolombia S.A. (Sociedad Anonima)", # row 67: desabbrev
        "Grupo México",                     # row 68: no change
        "Embraer Sociedad Anonima",         # row 69: replaced 'S.A.' -> 'Sociedad Anonima'
        "Cemex",                            # row 70: no change
        "LATAM Airlines Group",             # row 71: no change
        "Grupo Falabella",                  # row 72: no change
        "Tenaris",                          # row 73: no change
        "Ultrapar Participações Sociedad Anonima",  # row 74: replaced 'S.A.' -> 'Sociedad Anonima'
        "Grupo Carso",                      # row 75: no change
        "Grupo Argos",                      # row 76: no change
        "S.A.C.I. Falabella",               # row 77: left as-is (note: partial abbreviation remains)
        "Arcos Dorados Holdings Incorporated", # row 78: replaced 'Inc.' -> 'Incorporated'
        "JBS Sociedad Anonima",             # row 79: replaced 'S.A.' -> 'Sociedad Anonima'
        "Grupo Aeroportuario del Pacífico", # row 80: no change
        "Copel",                            # row 81: no change
        "Braskem",                          # row 82: no change
        "Grupo Antofagasta Minerals",       # row 83: no change
        "Ecopetrol",                        # row 84: no change
        "Banco do Brasil",                  # row 85: no change
        "Odebrecht Construction",           # row 86: added 'Construction'
        "YPF (Yacimientos Petrolíferos Fiscales)",  # row 87: no change, already spelled out
        "Marfrig Glboal Foods",             # row 88: typo 'Glboal'
        "Grupo Nutresa",                    # row 89: no change
        "SQM (Sociedad Química y Minera de Chile)", # row 90: no change
        "Petrobras Sociedad Anonima",       # row 91: replaced with 'Sociedad Anonima'
        "Vale Sociedad Anonima",            # row 92: replaced 'S.A.' -> 'Sociedad Anonima'
        "América Móvil Holdings",           # row 93: appended 'Holdings'
        "Itaú Unibanco Holding SA (Sociedad Anonima)",  # row 94: expanded 'S.A.'
        "Grupo México, Ltd",                # row 95: appended 'Ltd'
        "Banco Bradesco Sociedad Anonima",  # row 96: replaced 'S.A.' -> 'Sociedad Anonima'
        "Banco Santander Brasil",           # row 97: no change
        "Grupo Bimbo Foods",                # row 98: appended 'Foods'
        "Grupo Financiero Banorte",         # row 99: no change
        "Suzano Sociedad Anonima",          # row 100: replaced 'S.A.' -> 'Sociedad Anonima'
    ],
    "Customer Address": [
        "123 Elm Str, Sprinfgield, IL",       # row 1: changed 'St'->'Str', 'Springfield'->'Sprinfgield'
        "456 Oakk St, Metropolis, IN",        # row 2: changed 'Oak'->'Oakk'
        "789 Pine Str, Gottham, NY",          # row 3: 'St'->'Str', 'Gotham'->'Gottham'
        "101 Maple Ave, Smallville, KSS",     # row 4: 'KS'->'KSS'
        "102 Birch Street, Hil Valley, CA",   # row 5: 'Hill'->'Hil'
        "103 Cedr St, Sunnydale, CA",         # row 6: 'Cedar'->'Cedr'
        "104 Palm Street, Atlanits, FL",      # row 7: 'Atlantis'->'Atlanits'
        "105 Spruce St, Vice City, FL.",      # row 8: added '.' after FL
        "106 Iron Str, Star City, WAA",       # row 9: 'St'->'Str', 'WA'->'WAA'
        "107 Steel St, South Park, C0",       # row 10: 'CO'->'C0' (zero)
        "108 Silver Rd, Central City, MO",    # row 11: changed 'St'->'Rd'
        "109 Goold St, Emerald City, MI",     # row 12: 'Gold'->'Goold'
        "110 Coppr St, Kings Landing, CA",    # row 13: 'Copper'->'Coppr'
        "111 Zink St, Springfield, VT",       # row 14: 'Zinc'->'Zink'
        "112 Quartz St, Quahog, RR",          # row 15: 'RI'->'RR'
        "113 Cobalt St, Twin Peacks, WA",     # row 16: 'Peaks'->'Peacks'
        "114 Nickell St, Charming, CA",       # row 17: 'Nickel'->'Nickell'
        "115 Tinn St, Eureka, NV",            # row 18: 'Tin'->'Tinn'
        "116 Leadd St, Neptune, CA",          # row 19: 'Lead'->'Leadd'
        "117 Mercury Ave, Gothamm, NJ",       # row 20: 'Gotham'->'Gothamm'
        "118 Platinum St, Metropolis, TXS",   # row 21: 'TX'->'TXS'
        "119 Diamnod St, Pandora, AZ",        # row 22: 'Diamond'->'Diamnod'
        "120 Grphite St, Bon Temps, LA",      # row 23: 'Graphite'->'Grphite'
        "121 Silicon St, Silent Hill, MEE",   # row 24: 'ME'->'MEE'
        "122 Boroon St, Cabot Cove, ME",      # row 25: 'Boron'->'Boroon'
        "123 Argon St, Mystic Falls, VAa",    # row 26: 'VA'->'VAa'
        "124 Neon St, Twin Peaks, NV ",       # row 27: trailing space
        "125 Helium St, New New York, NY",    # row 28: no change (added second 'New' is original data)
        "126 Lithum St, Twin Peaks, WA",      # row 29: 'Lithium'->'Lithum'
        "127 Kryppton St, Smallville, TX",    # row 30: 'Krypton'->'Kryppton'
        "1600 Amphitheatre Pkwy, Muntain View, CA",    # row 31: 'Mountain'->'Muntain'
        "1 Apple Perk Way, Cupertino, CA",    # row 32: 'Park'->'Perk'
        "One Microsoft Wayy, Redmond, WA",    # row 33: 'Way'->'Wayy'
        "410 Terry Avenue N, Seatttle, WA",   # row 34: 'Seattle'->'Seatttle'
        "1 Hacker Way, Menlo Parkk, CA",      # row 35: 'Park'->'Parkk'
        "3500 Deer Creek Road, Palo Altoo, CA",  # row 36: 'Alto'->'Altoo'
        "3555 Farnamm St, Omaha, NE",         # row 37: 'Farnam'->'Farnamm'
        "900 Metro Cnter Blvd, Foster City, CA", # row 38: 'Center'->'Cnter'
        "One Johnson & Johson Plaza, New Brunswick, NJ", # row 39: 'Johnson'->'Johson'
        "129 Samsumg-Ro, Yeongtong-Gu, Suwon-si, South Korea", # row 40: 'Samsung'->'Samsumg'
        "5959 Las Colinas Bvld, Irving, TX",  # row 41: 'Blvd'->'Bvld'
        "702 SW 8th St, Bentonvile, AR",      # row 42: 'Bentonville'->'Bentonvile'
        "235 East 42nd Street, New Yorrk, NY",# row 43: 'York'->'Yorrk'
        "6001 Bollinger Canyon Rad, San Ramon, CA", # row 44: 'Road'->'Rad'
        "1 Coca Cola Palza, Atlanta, GA",     # row 45: 'Plaza'->'Palza'
        "1 Toyta-Cho, Toyota City, Japan",    # row 46: 'Toyota'->'Toyta'
        "Mercedesstraße 120, Stuttgrt, Germany", # row 47: 'Stuttgart'->'Stuttgrt'
        "2200 Mission Cllge Blvd, Santa Clara, CA", # row 48: 'College'->'Cllge'
        "1095 Avnue of the Americas, New York, NY", # row 49: 'Avenue'->'Avnue'
        "100 N Rverside Plaza, Chicago, IL",  # row 50: 'Riverside'->'Rverside'
        "500 Oracle Prkwy, Redwood City, CA", # row 51: 'Parkway'->'Prkwy'
        "One Bowrman Drive, Beaverton, OR",   # row 52: 'Bowerman'->'Bowrman'
        "1-7-1 Konan, Minato-kuu, Tokyo, Japan", # row 53: 'Minato-ku'->'Minato-kuu'
        "20 Yeouido-dong, Yeongdeungpo-g, Seoul, South Korea", # row 54: 'Yeongdeungpo-gu'->'Yeongdeungpo-g'
        "Carel van Bylandtlaan 16, The Hauge, Netherlands", # row 55: 'Hague'->'Hauge'
        "1 St Jame's Square, Londn, UK",      # row 56: 'London'->'Londn'
        "5 Neco St, Boston, MA",             # row 57: 'Necco'->'Neco'
        "300 Soth Tryon Street, Charlotte, NC", # row 58: 'South'->'Soth'
        "388 Greenwcih St, New York, NY",     # row 59: 'Greenwich'->'Greenwcih'
        "200 Vesey Str, New York, NY",        # row 60: 'St'->'Str'
        "Avenida República do Chille, 65, Rio de Janeiro, Brazil",  # row 61: 'Chile'->'Chille'
        "Lago Zurich 245, Plza Carso, Mexico City, Mexico",         # row 62: 'Plaza'->'Plza'
        "Praia de Botafgogo, 186, Rio de Janeiro, Brazil",          # row 63: 'Botafogo'->'Botafgogo'
        "Praça Alfredo Egydioo de Souza Aranha, 100, São Paulo, Brazil", # row 64: 'Egydio'->'Egydioo'
        "Arias 3751, Buenoss Aires, Argentina",  # row 65: 'Buenos'->'Buenoss'
        "Prolongación Pseo de la Reforma 1000, Mexico City, Mexico", # row 66: 'Paseo'->'Pseo'
        "Carrera 48 # 26-85, Medellín, Colobia", # row 67: 'Colombia'->'Colobia'
        "Campos Elíseos 400, Lmas de Chapultepec, Mexico City, Mexico", # row 68: 'Lomas'->'Lmas'
        "Av. Brig. Faria Lima, 2170, São José dos Campso, Brazil",   # row 69: 'Campos'->'Campso'
        "Av. Ricardo Margáin Zozya 325, San Pedro, Mexico",          # row 70: 'Zozaya'->'Zozya'
        "Av. Americo Vespucio 901, Renca, Satiago, Chile",           # row 71: 'Santiago'->'Satiago'
        "Rosas 1665, Santiagio, Chile",                              # row 72: 'Santiago'->'Santiagio'
        "Diagonal 185bis, Buenos Ares, Argentina",                   # row 73: 'Aires'->'Ares'
        "Rua Gomes de Carvlho, 1336, São Paulo, Brazil",             # row 74: 'Carvalho'->'Carvlho'
        "Lago Zrich 245, Plaza Carso, Mexico City, Mexico",          # row 75: 'Zurich'->'Zrich'
        "Carrera 43A #1A Sur - 143, Medllín, Colombia",              # row 76: 'Medellín'->'Medllín'
        "Rosas 1665, Satiago, Chile",                                # row 77: 'Santiago'->'Satiago'
        "Dr. Luis Bonavta 1294, Montevideo, Uruguay",                # row 78: 'Bonavita'->'Bonavta'
        "Avenida Marginal Diret do Tietê, 500, São Paulo, Brazil",   # row 79: 'Direita'->'Diret'
        "Mariano Otero 1249, Guadalajra, Mexico",                    # row 80: 'Guadalajara'->'Guadalajra'
        "Rua Coronel Dulcíddio, 800, Curitiba, Brazil",              # row 81: 'Dulcídio'->'Dulcíddio'
        "Rua Lemos Montiero, 120, São Paulo, Brazil",                # row 82: 'Monteiro'->'Montiero'
        "Av. Apoqundo 4001, Santiago, Chile",                        # row 83: 'Apoquindo'->'Apoqundo'
        "Calle 37 #8-43, Bogtá, Colombia",                           # row 84: 'Bogotá'->'Bogtá'
        "SBS Qadra 1 Bloco C, Brasília, Brazil",                     # row 85: 'Quadra'->'Qadra'
        "Av. das Nações Unids, 8501, São Paulo, Brazil",             # row 86: 'Unidas'->'Unids'
        "Macacha Güems 515, Buenos Aires, Argentina",                # row 87: 'Güemes'->'Güems'
        "Avenida Chedid Jafett, 222, São Paulo, Brazil",             # row 88: 'Jafet'->'Jafett'
        "Calle 73 #51-14, Medelín, Colombia",                        # row 89: 'Medellín'->'Medelín'
        "El Trovador 4285, Las Condess, Santiago, Chile",            # row 90: 'Condes'->'Condess'
        "Avenida República do Chile, 65, Rio de Jaineiro, Brazil",   # row 91: 'Janeiro'->'Jaineiro'
        "Praia de Botafgo, 186, Rio de Janeiro, Brazil",             # row 92: 'Botafogo'->'Botafgo'
        "Lago Zurich 245, Plaza Crso, Mexico City, Mexico",          # row 93: 'Carso'->'Crso'
        "Praça Alfredo Egydio de Souza Aranhha, 100, São Paulo, Brazil", # row 94: 'Aranha'->'Aranhha'
        "Campos Elíseos 400, Lomas de Chapultepec, Mexico Ciy, Mexico",  # row 95: 'City'->'Ciy'
        "Cidade de Deus, Vila Yar, Osasco, Brazil",                  # row 96: 'Yara'->'Yar'
        "Av. Presidente Juscelino Kubitshcek, 2041, São Paulo, Brazil", # row 97: 'Kubitschek'->'Kubitshcek'
        "Prolongación Paseo de la Refrma 1000, Mexico City, Mexico", # row 98: 'Reforma'->'Refrma'
        "Av. Revolución 3000, Monterrey, Mexic",                     # row 99: 'Mexico'->'Mexic'
        "Av. Professor Magalhães Nto, 1752, Salvador, Brazil"        # row 100: 'Neto'->'Nto'
    ],
    "Customer Industrial Sector": [
        "Manufacturing",               # row 1: no change
        "Technology",                  # row 2: no change
        "Food and Beverages",          # row 3: no change
        "Software",                    # row 4: no change
        "Real Eastate",                # row 5: typo 'Estate'->'Eastate'
        "Pharmaceuticals",             # row 6: no change
        "Technology",                  # row 7: no change
        "Finance",                     # row 8: no change
        "Biotechnoogy",               # row 9: 'Biotechnology'->'Biotechnoogy'
        "Food Processing",             # row 10: no change
        "Advanced Technology",         # row 11: no change
        "Conglomerate",                # row 12: no change
        "Beverages",                   # row 13: no change
        "Finance",                     # row 14: no change
        "Latex Manufacturing",         # row 15: no change
        "Retail",                      # row 16: no change
        "IT Serivces",                 # row 17: 'Services'->'Serivces'
        "Smelting",                    # row 18: no change
        "Propane and Propane Accessories",  # row 19: no change
        "Banking",                     # row 20: no change
        "Chemicals",                   # row 21: no change
        "Trade",                       # row 22: no change
        "Robtics",                     # row 23: 'Robotics'->'Robtics'
        "Film Studio",                 # row 24: no change
        "Import/Export",               # row 25: no change
        "Biotech",                     # row 26: no change
        "Defense",                     # row 27: no change
        "Delivery Servicess",          # row 28: 'Services'->'Servicess'
        "Food Production",             # row 29: no change
        "Investment Banking",          # row 30: no change
        "Technology",                  # row 31: no change
        "Technology",                  # row 32: no change
        "Technology",                  # row 33: no change
        "E-commece",                   # row 34: 'E-commerce'->'E-commece'
        "Social Media",                # row 35: no change
        "Automotive",                  # row 36: no change
        "Conglomerate",                # row 37: no change
        "Financial Servces",           # row 38: 'Services'->'Servces'
        "Pharmaceuticals",             # row 39: no change
        "Electronics",                 # row 40: no change
        "Oil and Gas",                 # row 41: no change
        "Retail",                      # row 42: no change
        "Pharmaceuticals",             # row 43: no change
        "Oil and Gas",                 # row 44: no change
        "Beverages",                   # row 45: no change
        "Automotive",                  # row 46: no change
        "Automtive",                   # row 47: 'Automotive'->'Automtive'
        "Semiconductors",              # row 48: no change
        "Telecommunications",          # row 49: no change
        "Aerospace and Defense",       # row 50: no change
        "Technology",                  # row 51: no change
        "Apparel",                     # row 52: no change
        "Electronics",                 # row 53: no change
        "Electronics",                 # row 54: no change
        "Oil and Gas",                 # row 55: no change
        "Oil and Gas",                 # row 56: no change
        "Conglomerate",                # row 57: no change
        "Conglomerrate",               # row 58: 'Conglomerate'->'Conglomerrate'
        "Financial Services",          # row 59: no change
        "Financial Services",          # row 60: no change
        "Oil and Gas",                 # row 61: no change
        "Telecommmunications",         # row 62: 'Telecommunications'->'Telecommmunications'
        "Mining",                      # row 63: no change
        "Banking",                     # row 64: no change
        "E-commerce",                  # row 65: no change
        "Food Processing",             # row 66: no change
        "Financial Services",          # row 67: no change
        "Conglomarate",                # row 68: 'Conglomerate'->'Conglomarate'
        "Aerospace and Defense",       # row 69: no change
        "Construction",                # row 70: no change
        "Aviation",                    # row 71: no change
        "Retail",                      # row 72: no change
        "Manufacturing",               # row 73: no change
        "Chemiccals",                  # row 74: 'Chemicals'->'Chemiccals'
        "Conglomerate",                # row 75: no change
        "Cement and Energy",           # row 76: no change
        "Retail",                      # row 77: no change
        "Fast Food",                   # row 78: no change
        "Food Processing",             # row 79: no change
        "Aviation",                    # row 80: no change
        "Energy",                      # row 81: no change
        "Petrochemicals",              # row 82: no change
        "Mining",                      # row 83: no change
        "Oil and Gas",                 # row 84: no change
        "Banking",                     # row 85: no change
        "Construction",                # row 86: no change
        "Oil and Gas",                 # row 87: no change
        "Food Processing",             # row 88: no change
        "Food and Beverages",          # row 89: no change
        "Chemiacals",                  # row 90: 'Chemicals'->'Chemiacals'
        "Oil and Gas",                 # row 91: no change
        "Mining",                      # row 92: no change
        "Telecommunications",          # row 93: no change
        "Banknig",                     # row 94: 'Banking'->'Banknig'
        "Mining",                      # row 95: no change
        "Banking",                     # row 96: no change
        "Banking",                     # row 97: no change
        "Food Processing",             # row 98: no change
        "Banking",                     # row 99: no change
        "Pulp and Paper"               # row 100: no change
    ]
}

from unidecode import unidecode
# Assuming 'fuzzy_data' is already defined
df_fuzzy = pd.DataFrame(fuzzy_data)

# Apply unidecode to all string columns
for col in df_fuzzy.select_dtypes(include=[object]):
    df_fuzzy[col] = df_fuzzy[col].apply(lambda x: unidecode(x) if isinstance(x, str) else x)

# Display the first few rows to verify
print(df_fuzzy.head())

csv_file_path_fuzzy = "./Sample_Dataset/Secondary_Data.csv"
df_fuzzy.to_csv(csv_file_path_fuzzy, index=False, encoding='utf-8')

   Customer ID                    Customer Name  \
0            1               Acme Cooorporation
1            2               Globex Corporation
2            3              Soylent Corporatoin
3            4  Initech LLC (Limited Liability)
4            5                    Bluth Company

                   Customer Address Customer Industrial Sector
0      123 Elm Str, Sprinfgield, IL              Manufacturing
1       456 Oakk St, Metropolis, IN                 Technology
2         789 Pine Str, Gottham, NY         Food and Beverages
3    101 Maple Ave, Smallville, KSS                   Software
4  102 Birch Street, Hil Valley, CA               Real Eastate